class MCPCapabilityRouterError(Exception):
    """Base exception for the runtime."""


class ConfigurationError(MCPCapabilityRouterError): ...


class ServerError(MCPCapabilityRouterError): ...


class ConnectionError(ServerError): ...


class AuthenticationError(ServerError): ...


class AuthorizationError(ServerError): ...


class ServerUnavailableError(ServerError): ...


class ProtocolError(ServerError): ...


class InvalidRequestError(MCPCapabilityRouterError): ...


class ToolExecutionError(MCPCapabilityRouterError): ...


class ResourceReadError(MCPCapabilityRouterError): ...


class PromptRetrievalError(MCPCapabilityRouterError): ...


class DiscoveryError(MCPCapabilityRouterError): ...


class RegistryError(MCPCapabilityRouterError): ...


class RetrievalError(MCPCapabilityRouterError): ...


class SelectionError(MCPCapabilityRouterError): ...


class LoadingError(MCPCapabilityRouterError): ...


class RefreshError(MCPCapabilityRouterError): ...


class ResilienceError(MCPCapabilityRouterError): ...


class TimeoutError(ResilienceError): ...


class CircuitOpenError(ResilienceError): ...


class RateLimitError(ResilienceError): ...


class CapabilityNotFoundError(RetrievalError): ...
